trigger:
- main

resources:
- repo: self

variables:
- name: cleanSourceBranch
  value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
- name: buildReasonRevisionNumberCounterSeed
  value: $[format('{0}-5', variables['CleanSourceBranch'])]
- name: buildReasonRevisionNumber
  value: $[counter(variables['buildReasonRevisionNumberCounterSeed'], 0)]
- name: versionTag
  value: '1.0.$(buildReasonRevisionNumber)'
- name: isMain
  value: $[eq(variables['cleanSourceBranch'], 'main')]
- name: shouldPublish
  value: $[eq(variables['isMain'], 'true')]

stages:
- stage: Build
  displayName: Build Docker image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build docker image
      inputs:
        command: 'build'
        containerRegistry: 'DockerHub - christianwut'
        repository: 'christianwut/xureverseproxy'
        Dockerfile: '$(Build.SourcesDirectory)/XuReverseProxy/Dockerfile'
        buildContext: '**/../'
        tags: |
          $(versionTag)
          latest
        arguments: --label branch=$(cleanSourceBranch)

    - task: Docker@2
      displayName: Push image to docker hub.docker.com
      condition: and(succeeded(), eq(variables['shouldPublish'], 'true'))
      inputs:
        command: 'push'
        containerRegistry: 'DockerHub - christianwut'
        repository: 'christianwut/xureverseproxy'
        tags: |
          $(versionTag)
          latest
