version: "3.3"
name: xureverseproxy-dev

###############################################
# This compose is for use during development. #
###############################################
#
# By default it only starts a database and a db admin interface.
# docker-compose up -d
#
# Use profile "backend" if you want to run the backend from a container instead of from your IDE of choice:
# docker-compose --profile backend up -d
#
# Use profile "frontend-watcher" if you want to build frontend from a container:
# docker-compose --profile frontend-watcher up -d

services:
  # Database
  db:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: Docker/db
      dockerfile: Dockerfile
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30

  # Database UI
  adminer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: adminer
    ports:
      - 8090:8080
    depends_on:
      db:
        condition: service_healthy

  # Backend
  backend:
    profiles: ["backend"]
    build:
      context: .
      dockerfile: XuReverseProxy/Dockerfile
    environment:
      - ConnectionStrings__DbConnection=Host=host.docker.internal; Port=5432; Database=postgres; Username=postgres; Password=postgres
      - Logging__LogLevel__Default=Information
      - ServerConfig__Domain__Scheme=https://
      - ServerConfig__Domain__Port=7272
      - ServerConfig__Domain__Domain=localdev.test
      - ServerConfig__Domain__AdminSubdomain=admin
    ports:
      - "7878:80"
    depends_on:
      - db

  # Frontend build watcher
  frontend-watcher:
    profiles: ["frontend-watcher"]
    build:
      context: .
      dockerfile: XuReverseProxy.Frontend/Dockerfile
    volumes:
      - ./XuReverseProxy.Frontend/src:/frontend/src
      - ./XuReverseProxy/wwwroot/dist:/XuReverseProxy/wwwroot/dist

  # Todo: dev db data seed container

