version: "3.3"
name: xureverseproxy

volumes:
  postgres-data:

services:
  # Backend
  backend:
    restart: unless-stopped
    image: christianwut/xureverseproxy:latest
    environment:
      # ServerConfig__Domain configs below should reflect the public url the proxy should be available on.
      - ServerConfig__Domain__Scheme=https://
      - ServerConfig__Domain__Port=443
      - ServerConfig__Domain__Domain=your-domain.com
      - ServerConfig__Domain__AdminSubdomain=admin # causes admin interfaces to be available on admin.your-domain.com
      - ConnectionStrings__DbConnection=Host=db; Port=5432; Database=postgres; Username=postgres; Password=postgres
      - Logging__LogLevel__Default=Information
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./cert:/https:ro
    ports:
      - "5252:80"
      - "7878:443"
    depends_on:
      - db

  # Database
  db:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.Database
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30

  # Database UI
  adminer:
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: adminer
    ports:
      - 8090:8080
    depends_on:
      db:
        condition: service_healthy
